### ISSUE TITLE
Images required for OneStory login redesign

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#1070]
* Need the logo - same size as existing JC logo
* Need new images for the login stages (goes over the yellow image on the left starting on Create Account page)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=819628619)

**Comment by GeorgeBellTMH** [comment]
Got the login stage images...just the logo left..

**Comment by lucastbelem** [comment]
@GeorgeBellTMH here is the logo.
![OSLogo_Black-01](https://user-images.githubusercontent.com/48295718/149048329-87a0cd14-0319-4155-89cb-5dd78c817f7f.png)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH could you pls change the text "made by a church. made for your church" to black instead of white?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH one more thing. These 2 paragraphs are appearing in the billing page. Maybe this is just happening in the dev page, but could you make sure that's not appearing at all? With the branding changes we don't need them at all.
<img width="1434" alt="Screen Shot 2022-01-11 at 8 42 05 PM" src="https://user-images.githubusercontent.com/48295718/149048919-15da2ba3-90b5-4b9f-a626-57e7769d2759.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this is minor, but can we align the text in this screen:
<img width="1438" alt="Screen Shot 2022-01-11 at 8 43 55 PM" src="https://user-images.githubusercontent.com/48295718/149049027-8900ed3b-aff2-4d59-af1b-ae8bd572e21f.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH only one problem to solve, I think.

When creating the profile, I click "save profile" for individual then "save profile' for the org profile. However, nothing happens. And there is no button for me to click to "proceed to platform". The only way to get in at that point is to refresh...once I do that I get in. Could you put a button there so that the user can proceed once both profiles are saved successfully? Or better yet, once they save the second one, and it fulfills all requirements, log them right in? 

Feel free to call me if you need any clarification. 

Other than this, it's ready to publish to beta.

**Comment by GeorgeBellTMH** [comment]
Logo and paragraph removed...

**Comment by GeorgeBellTMH** [comment]
made by a church. made for your church is now black
