### ISSUE TITLE
Grey bar on profile creation screen

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#230]
<img width="1408" alt="Screen Shot 2020-07-01 at 11 56 32 PM" src="https://user-images.githubusercontent.com/47749730/86314829-a69edf00-bbf6-11ea-9793-10d20b3d2766.png">

Grey bar when creating a user...

**Comment by mmacedom** [comment]
@GeorgeBellTMH I just signed up with a different email and I cannot get into the screen above. As soon as I entered my email, password, first and last name, I got an email confirmation with a confirmation code...I entered the confirmation code on the "confirmation code" field and it gave me an error saying that I cannot be confirmed because I was already confirmed. Then, it brought me back to the Sign in screen with email and pass. I signed in and got in and wasn't able to see this screen. Any clue why?

**Comment by mmacedom** [comment]
@GeorgeBellTMH How can I get to this screen on my local? I have tried a number of time and can only get to it on the live beta.

**Comment by mmacedom** [comment]
@GeorgeBellTMH I'm still trying to find this needle in the haystack.

**Comment by mmacedom** [comment]
@JonEsparaz That's awesome that you found this background!
