### ISSUE TITLE
First sign in

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#314]
It looks like the first time someone signs in after creating their account, the screen stays blank and refreshing doesn't fix it. You have to specifically re-type beta.jesuscollective.com to see your profile creation screen.

**Comment by GeorgeBellTMH** [comment]
I believe this is caused when you delete a user and then recreate...it navigates to the profile page instead of signupscreen3...I believe the solution is to navigate to root after deleting a user (or logging off)...also possible we need to navigate to signupscreen3 from all pages if the profile is not complete.

**Comment by GeorgeBellTMH** [comment]
Closing this...
