### ISSUE TITLE
Beta - a couple of profile pics aren't loading

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#392]
<img width="432" alt="Screen Shot 2020-08-05 at 2 08 21 PM" src="https://user-images.githubusercontent.com/48295718/89448152-2b64a780-d725-11ea-9708-6c6a0581266f.png">

**Comment by JonEsparaz** [comment]
I think this is an S3 issue @GeorgeBellTMH

**Comment by GeorgeBellTMH** [comment]
For future reference, this is due to the lambda function S3Trigger14f1cefa being run with:
npm install 
instead of: 
npm install --arch=x64 --platform=linux --target=12.2.0 

before being pushed...the Darwin binaries for sharp won't run on amazon linux (obviously...)

We probably need some sort of button in the admin that will regenerate missing photos...will create a ticket for that...

**Comment by GeorgeBellTMH** [comment]
#394 created

**Comment by GeorgeBellTMH** [comment]
(fixed on localhost)
