### ISSUE TITLE
Blank screen when creating user from non standard url

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#444]
When creating a user and your login started from a non standard url you may get a white screen...solution is to just enter the beta.jesuscollective.com url and try again...

**Comment by GeorgeBellTMH** [comment]
@lucastbelem can you test this on dev, I believe it is now fixed.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH no luck. I created a new user in dev under comm.admin@tmh and hit the blank screen. However, I believe the screen appear one screen deeper in. Previously, user would hit blank screen upon verification. Now I am able to verify, but when I re-enter email and password, I hit the blank screen instead of the profile screen.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH nevermind...I tried again with 2 other test emails and it worked. I think maybe it hadn't come through yet.

**Comment by CarrissaReffell** [comment]
@GeorgeBellTMH when I tested on mobile using user test.user3@tmh I hit a blank screen once I was able to verify. I couldn't see a profile screen load.

**Comment by lucastbelem** [comment]
@CarrissaReffell was it android or iOS?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I'm gonna close this for now until we receive more blank screen feedback.
