### ISSUE TITLE
CRM Design improvements

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#462]
@mmacedom could you please take a look at the CRM page in admin (under the rocket icon) and see what you can do to improve the design there? This is admin facing only, users don't see that, but it could use a bit of care. There is no approved design for this, so whatever you can do to improve it is great. 

I.e. problems:
- When you open a group, to close it you press the X, but it's not super clear
- When you open a group and then payment, it all stacks on top of each other and takes over the screen. Again, just not super clear on what's happening.

**Comment by GeorgeBellTMH** [comment]
CRM now loads all users...

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem I did some work this already last night but am not quite finished on it. I'll will keep working on it tonight.

**Comment by mmacedom** [comment]
@GeorgeBellTMH I did some more work on this screen and noticed that if you click on payment, then click on the "X" to delete any items that belong to payment, the group modal pops up. The behaviour seems odd but I'm not sure if that is part of a business requirement making it intentional. In any case, I thought I'd communicate that with you and @lucastbelem

**Comment by GeorgeBellTMH** [comment]
I think it's fixed in the latest version

**Comment by GeorgeBellTMH** [comment]
@mmacedom can you make the modal look more like this, we will be needing more of these...


![](https://uploads.sitepoint.com/wp-content/uploads/2014/02/1392433498bootstrap-modal-basic.jpg)


Title         X
------------
group1 X
group2 X
group3 X
Dropdown Add

**Comment by mmacedom** [comment]
@GeorgeBellTMH yes, I'll make them look like that

**Comment by mmacedom** [comment]
@GeorgeBellTMH I have fixed the Group modal and slightly modified the proposed layout to: 
Group 1 
Group 2
Group n
Dropdown
Add Button 

The reason for that is so that the modal fits as is on mobile. In terms of the order of items (top to bottom), it seems like the dropdown and add buttons should appear above the selected items. What are your thoughts on this? 

I still need to fix the Payment and need to fix the transparency of the dark background. 

<img width="454" alt="Screen Shot 2020-10-08 at 12 16 09 AM" src="https://user-images.githubusercontent.com/24467324/95414479-fd097100-08fb-11eb-84b3-faa861120e3d.png">

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I fixed the CRM page. Please let me know if there's anything else left to do on the Admin screens. Thx
