### ISSUE TITLE
Permissions Update

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#617]
We need the ability to make events/groups/resources etc available only to specific membership levels.

I.e. Curriculum only users should not have access to partner and event groups.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH the priority for this piece is specifically to keep curriculum users out of the dashboard...other permission needs can wait...but this is needed for paid launch Feb 15.

**Comment by GeorgeBellTMH** [comment]
Here's what I'm proposing....

1) We automatically send people with ky subscription to the ky overview page, unless they are also a partner or in a course
2) We make it so that the following happens:
a) Groups/Events/Courses/Resources/Orgs are only visible to the groups they are set to...(similar to the resource menu permissions)
b) Admins can set them to any permission set (ie Partner only, ky only, everyone)
c) Partners who are creating groups/events etc can only create groups that are seeable by other partners
d) If there are no visible groups/events/resources then on the homepage that section disapears

This way we can still create events and groups for the k&y, they can still get to them from the menu, and there is no major navigation changes needed...and everything works for everyone else as normal...and if they become partners+ky then they will see it all....

The nice thing about all this is that it will be very quick to develop...

Let me know if this is ok...I will do it tomorrow...

**Comment by GeorgeBellTMH** [comment]
My proposal for Connect with Others/User Directory is that everyone remains visible to each other...but that we allow for filtering to just partners, just ky...and maybe we default to just showing people similar to yourself...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this plan is great! Let's do it! :)

I'll ask Matt about the user directory bit, but I'd rather ask for forgiveness than permission at this point.

**Comment by GeorgeBellTMH** [comment]
Item 2 is done. Item 1 is #645. Item 3 to be created once confirmed.
