### ISSUE TITLE
Hide events/groups if there are no events/groups for that user

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#654]
If there are 0 groups/events then hide the item on the homepage.

**Comment by lucastbelem** [comment]
Can we also hide the navigation menu items for events and groups when that's the case too? 

If user is curriculum-only:

- Always land in the resource itself;
- Do not see events in the navigation when 0 events exist for which that user is permitted to see;
- JC logo is not clickable to the dashboard so that the user never sees the dashboard;

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I'm close this for now because Nathan's scope will involve thinking through this experience.
