### ISSUE TITLE
Scaled design elements

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#673]
Let's try something and see what happens. Can we scale down all containers and fonts for the profile page in dev to 1280px (66% of the mocked up sizes)? I'd love to see that and share with Matt and Katie and see how they feel about it. 

I picked the profile page because it feels like a simpler one to do as there are more variables in the dashboard page.

**Comment by lucastbelem** [comment]
@mmacedom any chance you'd have time to prioritize this today (if you're working today)? If so, @GeorgeBellTMH could you publish to beta tomorrow? I have a mtg tomorrow afternoon and would love to show this option and see how that feels for the stakeholders.

**Comment by GeorgeBellTMH** [comment]
@mmacedom please check out the scaling function of EStyleSheets - https://github.com/vitalets/react-native-extended-stylesheet

**Comment by mmacedom** [comment]
@lucastbelem I adjusted the container and font sizes in the "my profile page" as requested. The fonts seem too small. Please let me know what the feedback is. 

@GeorgeBellTMH I didn't have time to work through the scaling function and just manually adjusted the styles (I added "v2" of styles so that we can edit/remove/modify them if needed be).

**Comment by GeorgeBellTMH** [comment]
I am closing this, test complete, but not gonna work...
