### ISSUE TITLE
Add One Story Logo and lock ups to the JC Platform to increase alignment between OS marketing site and platform

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#871]
┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713124756)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can you pls add the logo to the overview page and or lockups to the age group pages? Attached are  mock ups for how to place and scale them. (No drop shadows pls). You should have the logos and lock ups in your inbox.

Can you please make this an uploadable field rather than fix the images in? JC is gonna add other resources in the next 2 weeks, so we can't have the One Story logos appearing for all of them, just for One Story.

**Comment by lucastbelem** [comment]
No longer relevant (and was completed).
